from typing import Any, Protocol


class Logger(Protocol):
    def log_config(self, cfg: Any) -> None: ...

    def log_metrics(self, metrics: dict[str, Any], step: int | None = None) -> None: ...

    def watch_model(self, model: Any) -> None: ...

    def finish(self) -> None: ...
