defaults:
  - model: nebium_base
  - training: kaggle
  - data: kaggle
  - logging: wandb
  - hub: huggingface
  - _self_

smoke_test: false

hydra:
  run:
    dir: /kaggle/working/outputs/${now:%Y-%m-%d_%H-%M-%S}
